// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WasmMT;
//
//    var pingQuery = PingQuery.FromJson(jsonString);

namespace WasmMT.Shared
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class PingQuery
    {
        [JsonProperty("$id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Id { get; set; }

        [JsonProperty("currentDateTime")]
        public string CurrentDateTime { get; set; }

        [JsonProperty("utcOffset")]
        public string UtcOffset { get; set; }

        [JsonProperty("isDayLightSavingsTime")]
        public bool IsDayLightSavingsTime { get; set; }

        [JsonProperty("dayOfTheWeek")]
        public string DayOfTheWeek { get; set; }

        [JsonProperty("timeZoneName")]
        public string TimeZoneName { get; set; }

        [JsonProperty("currentFileTime")]
        public double CurrentFileTime { get; set; }

        [JsonProperty("ordinalDate")]
        public string OrdinalDate { get; set; }

        [JsonProperty("serviceResponse")]
        public object ServiceResponse { get; set; }
    }

    public partial class PingQuery
    {
        public static PingQuery FromJson(string json) => JsonConvert.DeserializeObject<PingQuery>(json, WasmMT.Shared.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this PingQuery self) => JsonConvert.SerializeObject(self, WasmMT.Shared.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
